Old Homeworks
hrachtandilyan/designpatterns pull request #4
Opened 2019-04-01 17:22 UTC by narekhar

2019-04-03 12:17 UTC, narekhar commented
Old tasks + Singleton

2019-04-04 07:32 UTC, hrachtandilyan requested changes

2019-04-04 07:32 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
> +	Singleton& operator+(Singleton&&) = delete;
Probably a typo, should be assignment instead of addition operator

2019-04-04 07:32 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
> +		return this->_data;
No need for this->

2019-04-04 07:32 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
> +		this->_data = d;
No need for this->

2019-04-04 07:32 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
> +		if (_instance == 0) {
Make it thread safe

2019-04-04 10:45 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
> +mutex mtx;
Make this mutes static field for singleton class

2019-04-04 10:47 UTC, hrachtandilyan commented on 2019/Narek_Harutyunyan/Singleton.cpp
>  using namespace std;
Never use entire namespace. Add using statements for specific objects or write std:: prefix for all usages.

2020-02-14 12:57 UTC, merged